func.func @kernel_spmm(%arg0: tensor<?x?xf64, #sparse_tensor.encoding<{ map = (d0, d1) -> (d0 : compressed, d1 : compressed) }>>, %arg1: tensor<?x?xf64, #sparse_tensor.encoding<{ map = (d0, d1) -> (d0 : compressed, d1 : compressed) }>>, %arg2: tensor<?x?xf64, #sparse_tensor.encoding<{ map = (d0, d1) -> (d0 : compressed, d1 : compressed) }>>, %arg3: tensor<?x?xf64, #sparse_tensor.encoding<{ map = (d0, d1) -> (d0 : compressed, d1 : compressed) }>>, %arg4: tensor<?x?xf64, #sparse_tensor.encoding<{ map = (d0, d1) -> (d0 : compressed, d1 : compressed) }>>, %arg5: tensor<?x?xf64, #sparse_tensor.encoding<{ map = (d0, d1) -> (d0 : compressed, d1 : compressed) }>>, %arg6: tensor<?x?xf64, #sparse_tensor.encoding<{ map = (d0, d1) -> (d0 : compressed, d1 : compressed) }>>) -> tensor<?x?xf64, #sparse_tensor.encoding<{ map = (d0, d1) -> (d0 : compressed, d1 : compressed) }>> {
  %0 = "sam.generator"() : () -> tensor<index, #sam.encoding< Ref, "d0", "t2", "", 0 : i64>>
  %1 = "sam.generator"() : () -> tensor<index, #sam.encoding< Ref, "d0", "t0", "", 0 : i64>>
  %output_ref, %output_crd = "sam.fiber_lookup"(%1) <{index_var = 0 : index, tensor_num = 0 : index}> : (tensor<index, #sam.encoding< Ref, "d0", "t0", "", 0 : i64>>) -> (tensor<index, #sam.encoding< Ref, "d0", "t0", "compressed", 0 : i64>>, tensor<index, #sam.encoding< Crd, "d0", "t0", "compressed", 0 : i64>>)
  %2 = "sam.repeat"(%0, %output_ref) : (tensor<index, #sam.encoding< Ref, "d0", "t2", "", 0 : i64>>, tensor<index, #sam.encoding< Ref, "d0", "t0", "compressed", 0 : i64>>) -> tensor<index, #sam.encoding< Ref, "d0", "t2", "", 0 : i64>>
  %output_ref_0, %output_crd_1 = "sam.fiber_lookup"(%2) <{index_var = 3 : index, tensor_num = 2 : index}> : (tensor<index, #sam.encoding< Ref, "d0", "t2", "", 0 : i64>>) -> (tensor<index, #sam.encoding< Ref, "d3", "t2", "compressed", 1 : i64>>, tensor<index, #sam.encoding< Crd, "d3", "t2", "compressed", 1 : i64>>)
  %output_ref_2, %output_crd_3 = "sam.fiber_lookup"(%output_ref_0) <{index_var = 2 : index, tensor_num = 2 : index}> : (tensor<index, #sam.encoding< Ref, "d3", "t2", "compressed", 1 : i64>>) -> (tensor<index, #sam.encoding< Ref, "d2", "t2", "compressed", 0 : i64>>, tensor<index, #sam.encoding< Crd, "d2", "t2", "compressed", 0 : i64>>)
  %3 = "sam.generator"() : () -> tensor<index, #sam.encoding< Ref, "d0", "t1", "", 0 : i64>>
  %4 = "sam.repeat"(%3, %output_ref) : (tensor<index, #sam.encoding< Ref, "d0", "t1", "", 0 : i64>>, tensor<index, #sam.encoding< Ref, "d0", "t0", "compressed", 0 : i64>>) -> tensor<index, #sam.encoding< Ref, "d0", "t1", "", 0 : i64>>
  %5 = "sam.repeat"(%4, %output_ref_0) : (tensor<index, #sam.encoding< Ref, "d0", "t1", "", 0 : i64>>, tensor<index, #sam.encoding< Ref, "d3", "t2", "compressed", 1 : i64>>) -> tensor<index, #sam.encoding< Ref, "d3", "t1", "", 0 : i64>>
  %output_ref_4, %output_crd_5 = "sam.fiber_lookup"(%5) <{index_var = 2 : index, tensor_num = 1 : index}> : (tensor<index, #sam.encoding< Ref, "d3", "t1", "", 0 : i64>>) -> (tensor<index, #sam.encoding< Ref, "d2", "t1", "compressed", 1 : i64>>, tensor<index, #sam.encoding< Crd, "d2", "t1", "compressed", 1 : i64>>)
  %output_crd_6, %output_refs:2 = "sam.joiner"(%output_crd_3, %output_crd_5, %output_ref_2, %output_ref_4) <{joinerOp = #sam<joiner_type Intersect>, operandSegmentSizes = array<i32: 2, 2>}> : (tensor<index, #sam.encoding< Crd, "d2", "t2", "compressed", 0 : i64>>, tensor<index, #sam.encoding< Crd, "d2", "t1", "compressed", 1 : i64>>, tensor<index, #sam.encoding< Ref, "d2", "t2", "compressed", 0 : i64>>, tensor<index, #sam.encoding< Ref, "d2", "t1", "compressed", 1 : i64>>) -> (tensor<index, #sam.encoding< Crd, "d2", "", "dense", 0 : i64>>, tensor<index, #sam.encoding< Ref, "d2", "t1", "compressed", 0 : i64>>, tensor<index, #sam.encoding< Ref, "d2", "t2", "compressed", 0 : i64>>)
  %output_ref_7, %output_crd_8 = "sam.fiber_lookup"(%output_refs#0) <{index_var = 1 : index, tensor_num = 1 : index}> : (tensor<index, #sam.encoding< Ref, "d2", "t1", "compressed", 0 : i64>>) -> (tensor<index, #sam.encoding< Ref, "d1", "t1", "compressed", 0 : i64>>, tensor<index, #sam.encoding< Crd, "d1", "t1", "compressed", 0 : i64>>)
  %6 = "sam.repeat"(%output_ref, %output_ref_0) : (tensor<index, #sam.encoding< Ref, "d0", "t0", "compressed", 0 : i64>>, tensor<index, #sam.encoding< Ref, "d3", "t2", "compressed", 1 : i64>>) -> tensor<index, #sam.encoding< Ref, "d3", "t0", "", 0 : i64>>
  %7 = "sam.repeat"(%6, %output_refs#0) : (tensor<index, #sam.encoding< Ref, "d3", "t0", "", 0 : i64>>, tensor<index, #sam.encoding< Ref, "d2", "t1", "compressed", 0 : i64>>) -> tensor<index, #sam.encoding< Ref, "d2", "t0", "", 0 : i64>>
  %output_ref_9, %output_crd_10 = "sam.fiber_lookup"(%7) <{index_var = 1 : index, tensor_num = 0 : index}> : (tensor<index, #sam.encoding< Ref, "d2", "t0", "", 0 : i64>>) -> (tensor<index, #sam.encoding< Ref, "d1", "t0", "compressed", 1 : i64>>, tensor<index, #sam.encoding< Crd, "d1", "t0", "compressed", 1 : i64>>)
  %output_crd_11, %output_refs_12:2 = "sam.joiner"(%output_crd_8, %output_crd_10, %output_ref_7, %output_ref_9) <{joinerOp = #sam<joiner_type Intersect>, operandSegmentSizes = array<i32: 2, 2>}> : (tensor<index, #sam.encoding< Crd, "d1", "t1", "compressed", 0 : i64>>, tensor<index, #sam.encoding< Crd, "d1", "t0", "compressed", 1 : i64>>, tensor<index, #sam.encoding< Ref, "d1", "t1", "compressed", 0 : i64>>, tensor<index, #sam.encoding< Ref, "d1", "t0", "compressed", 1 : i64>>) -> (tensor<index, #sam.encoding< Crd, "d1", "", "dense", 0 : i64>>, tensor<index, #sam.encoding< Ref, "d1", "t0", "compressed", 0 : i64>>, tensor<index, #sam.encoding< Ref, "d1", "t1", "compressed", 0 : i64>>)
  %8 = "sam.array_val"(%output_refs_12#0) <{stream_shape = array<i64: 1>}> : (tensor<index, #sam.encoding< Ref, "d1", "t0", "compressed", 0 : i64>>) -> tensor<f64, #sam.encoding< Val, "d0", "t0", "", 0 : i64>>
  %9 = "sam.array_val"(%output_refs_12#1) <{stream_shape = array<i64: 1>}> : (tensor<index, #sam.encoding< Ref, "d1", "t1", "compressed", 0 : i64>>) -> tensor<f64, #sam.encoding< Val, "d0", "t1", "", 0 : i64>>
  %10 = "sam.alu"(%8, %9) <{aluOp = #sam<op_type Mul>}> : (tensor<f64, #sam.encoding< Val, "d0", "t0", "", 0 : i64>>, tensor<f64, #sam.encoding< Val, "d0", "t1", "", 0 : i64>>) -> tensor<f64, #sam.encoding< Val, "d0", "t", "", 0 : i64>>
  %11 = "sam.reduce"(%10) <{reduceType = #sam<reduce_type Add>}> : (tensor<f64, #sam.encoding< Val, "d0", "t", "", 0 : i64>>) -> tensor<f64, #sam.encoding< Val, "d0", "t", "", 0 : i64>>
  %12 = "sam.array_val"(%output_refs#1) <{stream_shape = array<i64: 1>}> : (tensor<index, #sam.encoding< Ref, "d2", "t2", "compressed", 0 : i64>>) -> tensor<f64, #sam.encoding< Val, "d0", "t2", "", 0 : i64>>
  %13 = "sam.alu"(%11, %12) <{aluOp = #sam<op_type Mul>}> : (tensor<f64, #sam.encoding< Val, "d0", "t", "", 0 : i64>>, tensor<f64, #sam.encoding< Val, "d0", "t2", "", 0 : i64>>) -> tensor<f64, #sam.encoding< Val, "d0", "t", "", 0 : i64>>
  %14 = "sam.reduce"(%13) <{reduceType = #sam<reduce_type Add>}> : (tensor<f64, #sam.encoding< Val, "d0", "t", "", 0 : i64>>) -> tensor<f64, #sam.encoding< Val, "d0", "t", "", 0 : i64>>
  %15 = linalg.matmul ins(%arg0, %arg1 : tensor<?x?xf64, #sparse_tensor.encoding<{ map = (d0, d1) -> (d0 : compressed, d1 : compressed) }>>, tensor<?x?xf64, #sparse_tensor.encoding<{ map = (d0, d1) -> (d0 : compressed, d1 : compressed) }>>) outs(%arg6 : tensor<?x?xf64, #sparse_tensor.encoding<{ map = (d0, d1) -> (d0 : compressed, d1 : compressed) }>>) -> tensor<?x?xf64, #sparse_tensor.encoding<{ map = (d0, d1) -> (d0 : compressed, d1 : compressed) }>>
  %16 = linalg.matmul ins(%15, %arg2 : tensor<?x?xf64, #sparse_tensor.encoding<{ map = (d0, d1) -> (d0 : compressed, d1 : compressed) }>>, tensor<?x?xf64, #sparse_tensor.encoding<{ map = (d0, d1) -> (d0 : compressed, d1 : compressed) }>>) outs(%arg6 : tensor<?x?xf64, #sparse_tensor.encoding<{ map = (d0, d1) -> (d0 : compressed, d1 : compressed) }>>) -> tensor<?x?xf64, #sparse_tensor.encoding<{ map = (d0, d1) -> (d0 : compressed, d1 : compressed) }>>
  return %16 : tensor<?x?xf64, #sparse_tensor.encoding<{ map = (d0, d1) -> (d0 : compressed, d1 : compressed) }>>
}