// BEGIN GENERATED MLIR CODE
// t10-0,1: dims(2), vars(i0, i1), mode_order(0, 1)
// t8-0,1: dims(2), vars(i1, i2), mode_order(0, 1)
// t6-0,1: dims(2), vars(i2, i3), mode_order(0, 1)
// t9-0: dims(1), vars(i3), mode_order(0)
// t10-0,1: dims(2), vars(i1, i4), mode_order(0, 1)
// t8-0,1: dims(2), vars(i4, i5), mode_order(0, 1)
// t11-0,1: dims(2), vars(i5, i3), mode_order(0, 1)
// t3-0: dims(1), vars(i3), mode_order(0)
// t4-0,1: dims(2), vars(i3, i6), mode_order(0, 1)
// t5-0: dims(1), vars(i6), mode_order(0)
module attributes {torch.debug_module_name = "CustomGraphSAGE"} {
  ml_program.global private mutable @global_seed(dense<0> : tensor<i64>) : tensor<i64>
  func.func @forward(%arg0: tensor<1767x50xf32>, %arg1: tensor<1767x1767xf32>, %arg2: tensor<16xf32>, %arg3: tensor<50x16xf32>, %arg4: tensor<121xf32>, %arg5: tensor<16x121xf32>) -> tensor<f32, #sam.encoding< Val, "d0", "t", "", 0 : i64>> {
    %0 = "sam.generator"() : () -> tensor<index, #sam.encoding< Ref, "d0", "t10-0,1", "", 0 : i64>>
    %output_ref, %output_crd = "sam.fiber_lookup"(%0) <{index_var = 0 : index, tensor_num = 10 : index}> : (tensor<index, #sam.encoding< Ref, "d0", "t10-0,1", "", 0 : i64>>) -> (tensor<index, #sam.encoding< Ref, "d0", "t10-0,1", "dense", 0 : i64>>, tensor<index, #sam.encoding< Crd, "d0", "t10-0,1", "dense", 0 : i64>>)
    %output_ref_0, %output_crd_1 = "sam.fiber_lookup"(%output_ref) <{index_var = 1 : index, tensor_num = 10 : index}> : (tensor<index, #sam.encoding< Ref, "d0", "t10-0,1", "dense", 0 : i64>>) -> (tensor<index, #sam.encoding< Ref, "d1", "t10-0,1", "dense", 1 : i64>>, tensor<index, #sam.encoding< Crd, "d1", "t10-0,1", "dense", 1 : i64>>)
    %1 = "sam.generator"() : () -> tensor<index, #sam.encoding< Ref, "d0", "t8-0,1", "", 0 : i64>>
    %2 = "sam.repeat"(%1, %output_ref) : (tensor<index, #sam.encoding< Ref, "d0", "t8-0,1", "", 0 : i64>>, tensor<index, #sam.encoding< Ref, "d0", "t10-0,1", "dense", 0 : i64>>) -> tensor<index, #sam.encoding< Ref, "d0", "t8-0,1", "", 0 : i64>>
    %output_ref_2, %output_crd_3 = "sam.fiber_lookup"(%2) <{index_var = 1 : index, tensor_num = 8 : index}> : (tensor<index, #sam.encoding< Ref, "d0", "t8-0,1", "", 0 : i64>>) -> (tensor<index, #sam.encoding< Ref, "d1", "t8-0,1", "dense", 0 : i64>>, tensor<index, #sam.encoding< Crd, "d1", "t8-0,1", "dense", 0 : i64>>)
    %output_crd_4, %output_refs:2 = "sam.joiner"(%output_crd_1, %output_crd_3, %output_ref_0, %output_ref_2) <{joinerOp = #sam<joiner_type Intersect>, operandSegmentSizes = array<i32: 2, 2>}> : (tensor<index, #sam.encoding< Crd, "d1", "t10-0,1", "dense", 1 : i64>>, tensor<index, #sam.encoding< Crd, "d1", "t8-0,1", "dense", 0 : i64>>, tensor<index, #sam.encoding< Ref, "d1", "t10-0,1", "dense", 1 : i64>>, tensor<index, #sam.encoding< Ref, "d1", "t8-0,1", "dense", 0 : i64>>) -> (tensor<index, #sam.encoding< Crd, "d1", "", "dense", 0 : i64>>, tensor<index, #sam.encoding< Ref, "d1", "t10-0,1", "dense", 1 : i64>>, tensor<index, #sam.encoding< Ref, "d1", "t8-0,1", "dense", 0 : i64>>)
    %3 = "sam.repeat"(%0, %output_ref) : (tensor<index, #sam.encoding< Ref, "d0", "t10-0,1", "", 0 : i64>>, tensor<index, #sam.encoding< Ref, "d0", "t10-0,1", "dense", 0 : i64>>) -> tensor<index, #sam.encoding< Ref, "d0", "t10-0,1", "", 0 : i64>>
    %output_ref_5, %output_crd_6 = "sam.fiber_lookup"(%3) <{index_var = 1 : index, tensor_num = 10 : index}> : (tensor<index, #sam.encoding< Ref, "d0", "t10-0,1", "", 0 : i64>>) -> (tensor<index, #sam.encoding< Ref, "d1", "t10-0,1", "dense", 0 : i64>>, tensor<index, #sam.encoding< Crd, "d1", "t10-0,1", "dense", 0 : i64>>)
    %output_crd_7, %output_refs_8:3 = "sam.joiner"(%output_crd_4, %output_crd_4, %output_crd_6, %output_refs#0, %output_refs#1, %output_ref_5) <{joinerOp = #sam<joiner_type Union>, operandSegmentSizes = array<i32: 3, 3>}> : (tensor<index, #sam.encoding< Crd, "d1", "", "dense", 0 : i64>>, tensor<index, #sam.encoding< Crd, "d1", "", "dense", 0 : i64>>, tensor<index, #sam.encoding< Crd, "d1", "t10-0,1", "dense", 0 : i64>>, tensor<index, #sam.encoding< Ref, "d1", "t10-0,1", "dense", 1 : i64>>, tensor<index, #sam.encoding< Ref, "d1", "t8-0,1", "dense", 0 : i64>>, tensor<index, #sam.encoding< Ref, "d1", "t10-0,1", "dense", 0 : i64>>) -> (tensor<index, #sam.encoding< Crd, "d1", "", "dense", 0 : i64>>, tensor<index, #sam.encoding< Ref, "d1", "t10-0,1", "dense", 1 : i64>>, tensor<index, #sam.encoding< Ref, "d1", "t8-0,1", "dense", 0 : i64>>, tensor<index, #sam.encoding< Ref, "d1", "t10-0,1", "dense", 0 : i64>>)
    %output_ref_9, %output_crd_10 = "sam.fiber_lookup"(%output_refs_8#1) <{index_var = 2 : index, tensor_num = 8 : index}> : (tensor<index, #sam.encoding< Ref, "d1", "t8-0,1", "dense", 0 : i64>>) -> (tensor<index, #sam.encoding< Ref, "d2", "t8-0,1", "dense", 1 : i64>>, tensor<index, #sam.encoding< Crd, "d2", "t8-0,1", "dense", 1 : i64>>)
    %4 = "sam.generator"() : () -> tensor<index, #sam.encoding< Ref, "d0", "t6-0,1", "", 0 : i64>>
    %5 = "sam.repeat"(%4, %output_ref) : (tensor<index, #sam.encoding< Ref, "d0", "t6-0,1", "", 0 : i64>>, tensor<index, #sam.encoding< Ref, "d0", "t10-0,1", "dense", 0 : i64>>) -> tensor<index, #sam.encoding< Ref, "d0", "t6-0,1", "", 0 : i64>>
    %6 = "sam.repeat"(%5, %output_refs_8#1) : (tensor<index, #sam.encoding< Ref, "d0", "t6-0,1", "", 0 : i64>>, tensor<index, #sam.encoding< Ref, "d1", "t8-0,1", "dense", 0 : i64>>) -> tensor<index, #sam.encoding< Ref, "d1", "t6-0,1", "", 0 : i64>>
    %output_ref_11, %output_crd_12 = "sam.fiber_lookup"(%6) <{index_var = 2 : index, tensor_num = 6 : index}> : (tensor<index, #sam.encoding< Ref, "d1", "t6-0,1", "", 0 : i64>>) -> (tensor<index, #sam.encoding< Ref, "d2", "t6-0,1", "dense", 0 : i64>>, tensor<index, #sam.encoding< Crd, "d2", "t6-0,1", "dense", 0 : i64>>)
    %output_crd_13, %output_refs_14:2 = "sam.joiner"(%output_crd_10, %output_crd_12, %output_ref_9, %output_ref_11) <{joinerOp = #sam<joiner_type Intersect>, operandSegmentSizes = array<i32: 2, 2>}> : (tensor<index, #sam.encoding< Crd, "d2", "t8-0,1", "dense", 1 : i64>>, tensor<index, #sam.encoding< Crd, "d2", "t6-0,1", "dense", 0 : i64>>, tensor<index, #sam.encoding< Ref, "d2", "t8-0,1", "dense", 1 : i64>>, tensor<index, #sam.encoding< Ref, "d2", "t6-0,1", "dense", 0 : i64>>) -> (tensor<index, #sam.encoding< Crd, "d2", "", "dense", 0 : i64>>, tensor<index, #sam.encoding< Ref, "d2", "t8-0,1", "dense", 1 : i64>>, tensor<index, #sam.encoding< Ref, "d2", "t6-0,1", "dense", 0 : i64>>)
    %output_ref_15, %output_crd_16 = "sam.fiber_lookup"(%output_refs_14#1) <{index_var = 3 : index, tensor_num = 6 : index}> : (tensor<index, #sam.encoding< Ref, "d2", "t6-0,1", "dense", 0 : i64>>) -> (tensor<index, #sam.encoding< Ref, "d3", "t6-0,1", "dense", 1 : i64>>, tensor<index, #sam.encoding< Crd, "d3", "t6-0,1", "dense", 1 : i64>>)
    %7 = "sam.repeat"(%output_refs_14#0, %output_ref_15) : (tensor<index, #sam.encoding< Ref, "d2", "t8-0,1", "dense", 1 : i64>>, tensor<index, #sam.encoding< Ref, "d3", "t6-0,1", "dense", 1 : i64>>) -> tensor<index, #sam.encoding< Ref, "d3", "t8-0,1", "", 0 : i64>>
    %8 = "sam.array_val"(%7) <{stream_shape = array<i64: 1>}> : (tensor<index, #sam.encoding< Ref, "d3", "t8-0,1", "", 0 : i64>>) -> tensor<f32, #sam.encoding< Val, "d0", "t8-0,1", "", 0 : i64>>
    %9 = "sam.array_val"(%output_ref_15) <{stream_shape = array<i64: 1>}> : (tensor<index, #sam.encoding< Ref, "d3", "t6-0,1", "dense", 1 : i64>>) -> tensor<f32, #sam.encoding< Val, "d0", "t6-0,1", "", 0 : i64>>
    %10 = "sam.alu"(%8, %9) <{aluOp = #sam<op_type Mul>}> : (tensor<f32, #sam.encoding< Val, "d0", "t8-0,1", "", 0 : i64>>, tensor<f32, #sam.encoding< Val, "d0", "t6-0,1", "", 0 : i64>>) -> tensor<f32, #sam.encoding< Val, "d0", "t", "", 0 : i64>>
    %output_inner_crd, %output_val = "sam.spacc"(%output_crd_16, %output_crd_13, %10) <{order = 1 : index}> : (tensor<index, #sam.encoding< Crd, "d3", "t6-0,1", "dense", 1 : i64>>, tensor<index, #sam.encoding< Crd, "d2", "", "dense", 0 : i64>>, tensor<f32, #sam.encoding< Val, "d0", "t", "", 0 : i64>>) -> (tensor<index, #sam.encoding< Crd, "d3", "t6-0,1", "dense", 1 : i64>>, tensor<f32, #sam.encoding< Val, "d0", "t", "", 0 : i64>>)
    %11 = "sam.generator"() : () -> tensor<index, #sam.encoding< Ref, "d0", "t4-0,1", "", 0 : i64>>
    %12 = "sam.repeat"(%11, %output_ref) : (tensor<index, #sam.encoding< Ref, "d0", "t4-0,1", "", 0 : i64>>, tensor<index, #sam.encoding< Ref, "d0", "t10-0,1", "dense", 0 : i64>>) -> tensor<index, #sam.encoding< Ref, "d0", "t4-0,1", "", 0 : i64>>

    %output_ref_17, %output_crd_18 = "sam.fiber_lookup"(%12) <{index_var = 3 : index, tensor_num = 4 : index}> : (tensor<index, #sam.encoding< Ref, "d0", "t4-0,1", "", 0 : i64>>) -> (tensor<index, #sam.encoding< Ref, "d3", "t4-0,1", "dense", 0 : i64>>, tensor<index, #sam.encoding< Crd, "d3", "t4-0,1", "dense", 0 : i64>>)

    //%output_crd_19, %output_refs_20:2 = "sam.joiner"(%output_inner_crd, %output_crd_18, %output_val, %output_ref_17) <{joinerOp = #sam<joiner_type Intersect>, operandSegmentSizes = array<i32: 2, 2>}> : (tensor<index, #sam.encoding< Crd, "d3", "t6-0,1", "dense", 1 : i64>>, tensor<index, #sam.encoding< Crd, "d3", "t4-0,1", "dense", 0 : i64>>, tensor<f32, #sam.encoding< Val, "d0", "t", "", 0 : i64>>, tensor<index, #sam.encoding< Ref, "d3", "t4-0,1", "dense", 0 : i64>>) -> (tensor<index, #sam.encoding< Crd, "d3", "", "dense", 0 : i64>>, tensor<f32, #sam.encoding< Val, "d0", "t", "", 0 : i64>>, tensor<index, #sam.encoding< Ref, "d3", "t4-0,1", "dense", 0 : i64>>)

    %13 = "sam.generator"() : () -> tensor<index, #sam.encoding< Ref, "d0", "t9-0", "", 0 : i64>>
    %14 = "sam.repeat"(%13, %output_ref) : (tensor<index, #sam.encoding< Ref, "d0", "t9-0", "", 0 : i64>>, tensor<index, #sam.encoding< Ref, "d0", "t10-0,1", "dense", 0 : i64>>) -> tensor<index, #sam.encoding< Ref, "d0", "t9-0", "", 0 : i64>>
    %15 = "sam.repeat"(%14, %output_refs_8#1) : (tensor<index, #sam.encoding< Ref, "d0", "t9-0", "", 0 : i64>>, tensor<index, #sam.encoding< Ref, "d1", "t8-0,1", "dense", 0 : i64>>) -> tensor<index, #sam.encoding< Ref, "d1", "t9-0", "", 0 : i64>>
    %output_ref_21, %output_crd_22 = "sam.fiber_lookup"(%15) <{index_var = 3 : index, tensor_num = 9 : index}> : (tensor<index, #sam.encoding< Ref, "d1", "t9-0", "", 0 : i64>>) -> (tensor<index, #sam.encoding< Ref, "d3", "t9-0", "dense", 0 : i64>>, tensor<index, #sam.encoding< Crd, "d3", "t9-0", "dense", 0 : i64>>)
    %output_ref_23, %output_crd_24 = "sam.fiber_lookup"(%output_refs_8#2) <{index_var = 4 : index, tensor_num = 10 : index}> : (tensor<index, #sam.encoding< Ref, "d1", "t10-0,1", "dense", 0 : i64>>) -> (tensor<index, #sam.encoding< Ref, "d4", "t10-0,1", "dense", 1 : i64>>, tensor<index, #sam.encoding< Crd, "d4", "t10-0,1", "dense", 1 : i64>>)
    %16 = "sam.repeat"(%2, %output_refs_8#2) : (tensor<index, #sam.encoding< Ref, "d0", "t8-0,1", "", 0 : i64>>, tensor<index, #sam.encoding< Ref, "d1", "t10-0,1", "dense", 0 : i64>>) -> tensor<index, #sam.encoding< Ref, "d1", "t8-0,1", "", 0 : i64>>
    %output_ref_25, %output_crd_26 = "sam.fiber_lookup"(%16) <{index_var = 4 : index, tensor_num = 8 : index}> : (tensor<index, #sam.encoding< Ref, "d1", "t8-0,1", "", 0 : i64>>) -> (tensor<index, #sam.encoding< Ref, "d4", "t8-0,1", "dense", 0 : i64>>, tensor<index, #sam.encoding< Crd, "d4", "t8-0,1", "dense", 0 : i64>>)
    %output_crd_27, %output_refs_28:2 = "sam.joiner"(%output_crd_24, %output_crd_26, %output_ref_23, %output_ref_25) <{joinerOp = #sam<joiner_type Intersect>, operandSegmentSizes = array<i32: 2, 2>}> : (tensor<index, #sam.encoding< Crd, "d4", "t10-0,1", "dense", 1 : i64>>, tensor<index, #sam.encoding< Crd, "d4", "t8-0,1", "dense", 0 : i64>>, tensor<index, #sam.encoding< Ref, "d4", "t10-0,1", "dense", 1 : i64>>, tensor<index, #sam.encoding< Ref, "d4", "t8-0,1", "dense", 0 : i64>>) -> (tensor<index, #sam.encoding< Crd, "d4", "", "dense", 0 : i64>>, tensor<index, #sam.encoding< Ref, "d4", "t10-0,1", "dense", 1 : i64>>, tensor<index, #sam.encoding< Ref, "d4", "t8-0,1", "dense", 0 : i64>>)
    %output_ref_29, %output_crd_30 = "sam.fiber_lookup"(%output_refs_28#1) <{index_var = 5 : index, tensor_num = 8 : index}> : (tensor<index, #sam.encoding< Ref, "d4", "t8-0,1", "dense", 0 : i64>>) -> (tensor<index, #sam.encoding< Ref, "d5", "t8-0,1", "dense", 1 : i64>>, tensor<index, #sam.encoding< Crd, "d5", "t8-0,1", "dense", 1 : i64>>)
    %17 = "sam.repeat"(%output_refs_28#0, %output_ref_29) : (tensor<index, #sam.encoding< Ref, "d4", "t10-0,1", "dense", 1 : i64>>, tensor<index, #sam.encoding< Ref, "d5", "t8-0,1", "dense", 1 : i64>>) -> tensor<index, #sam.encoding< Ref, "d5", "t10-0,1", "", 0 : i64>>
    %18 = "sam.array_val"(%17) <{stream_shape = array<i64: 1>}> : (tensor<index, #sam.encoding< Ref, "d5", "t10-0,1", "", 0 : i64>>) -> tensor<f32, #sam.encoding< Val, "d0", "t10-0,1", "", 0 : i64>>
    %19 = "sam.array_val"(%output_ref_29) <{stream_shape = array<i64: 1>}> : (tensor<index, #sam.encoding< Ref, "d5", "t8-0,1", "dense", 1 : i64>>) -> tensor<f32, #sam.encoding< Val, "d0", "t8-0,1", "", 0 : i64>>
    %20 = "sam.alu"(%18, %19) <{aluOp = #sam<op_type Mul>}> : (tensor<f32, #sam.encoding< Val, "d0", "t10-0,1", "", 0 : i64>>, tensor<f32, #sam.encoding< Val, "d0", "t8-0,1", "", 0 : i64>>) -> tensor<f32, #sam.encoding< Val, "d0", "t", "", 0 : i64>>
    %output_inner_crd_31, %output_val_32 = "sam.spacc"(%output_crd_30, %output_crd_27, %20) <{order = 1 : index}> : (tensor<index, #sam.encoding< Crd, "d5", "t8-0,1", "dense", 1 : i64>>, tensor<index, #sam.encoding< Crd, "d4", "", "dense", 0 : i64>>, tensor<f32, #sam.encoding< Val, "d0", "t", "", 0 : i64>>) -> (tensor<index, #sam.encoding< Crd, "d5", "t8-0,1", "dense", 1 : i64>>, tensor<f32, #sam.encoding< Val, "d0", "t", "", 0 : i64>>)
    %21 = "sam.generator"() : () -> tensor<index, #sam.encoding< Ref, "d0", "t11-0,1", "", 0 : i64>>
    %22 = "sam.repeat"(%21, %output_ref) : (tensor<index, #sam.encoding< Ref, "d0", "t11-0,1", "", 0 : i64>>, tensor<index, #sam.encoding< Ref, "d0", "t10-0,1", "dense", 0 : i64>>) -> tensor<index, #sam.encoding< Ref, "d0", "t11-0,1", "", 0 : i64>>
    %23 = "sam.repeat"(%22, %output_refs_8#2) : (tensor<index, #sam.encoding< Ref, "d0", "t11-0,1", "", 0 : i64>>, tensor<index, #sam.encoding< Ref, "d1", "t10-0,1", "dense", 0 : i64>>) -> tensor<index, #sam.encoding< Ref, "d1", "t11-0,1", "", 0 : i64>>
    %output_ref_33, %output_crd_34 = "sam.fiber_lookup"(%23) <{index_var = 5 : index, tensor_num = 11 : index}> : (tensor<index, #sam.encoding< Ref, "d1", "t11-0,1", "", 0 : i64>>) -> (tensor<index, #sam.encoding< Ref, "d5", "t11-0,1", "dense", 0 : i64>>, tensor<index, #sam.encoding< Crd, "d5", "t11-0,1", "dense", 0 : i64>>)
    %output_crd_35, %output_refs_36:2 = "sam.joiner"(%output_inner_crd_31, %output_crd_34, %output_val_32, %output_ref_33) <{joinerOp = #sam<joiner_type Intersect>, operandSegmentSizes = array<i32: 2, 2>}> : (tensor<index, #sam.encoding< Crd, "d5", "t8-0,1", "dense", 1 : i64>>, tensor<index, #sam.encoding< Crd, "d5", "t11-0,1", "dense", 0 : i64>>, tensor<f32, #sam.encoding< Val, "d0", "t", "", 0 : i64>>, tensor<index, #sam.encoding< Ref, "d5", "t11-0,1", "dense", 0 : i64>>) -> (tensor<index, #sam.encoding< Crd, "d5", "", "dense", 0 : i64>>, tensor<f32, #sam.encoding< Val, "d0", "t", "", 0 : i64>>, tensor<index, #sam.encoding< Ref, "d5", "t11-0,1", "dense", 0 : i64>>)
    %output_ref_37, %output_crd_38 = "sam.fiber_lookup"(%output_refs_36#1) <{index_var = 3 : index, tensor_num = 11 : index}> : (tensor<index, #sam.encoding< Ref, "d5", "t11-0,1", "dense", 0 : i64>>) -> (tensor<index, #sam.encoding< Ref, "d3", "t11-0,1", "dense", 1 : i64>>, tensor<index, #sam.encoding< Crd, "d3", "t11-0,1", "dense", 1 : i64>>)
    %24 = "sam.array_val"(%output_ref_37) <{stream_shape = array<i64: 1>}> : (tensor<index, #sam.encoding< Ref, "d3", "t11-0,1", "dense", 1 : i64>>) -> tensor<f32, #sam.encoding< Val, "d0", "t11-0,1", "", 0 : i64>>
    %25 = "sam.repeat"(%output_refs_36#0, %output_ref_37) : (tensor<f32, #sam.encoding< Val, "d0", "t", "", 0 : i64>>, tensor<index, #sam.encoding< Ref, "d3", "t11-0,1", "dense", 1 : i64>>) -> tensor<f32, #sam.encoding< Ref, "d3", "t", "", 0 : i64>>
    %26 = "sam.alu"(%25, %24) <{aluOp = #sam<op_type Mul>}> : (tensor<f32, #sam.encoding< Ref, "d3", "t", "", 0 : i64>>, tensor<f32, #sam.encoding< Val, "d0", "t11-0,1", "", 0 : i64>>) -> tensor<f32, #sam.encoding< Val, "d0", "t", "", 0 : i64>>
    %output_inner_crd_39, %output_val_40 = "sam.spacc"(%output_crd_38, %output_crd_35, %26) <{order = 1 : index}> : (tensor<index, #sam.encoding< Crd, "d3", "t11-0,1", "dense", 1 : i64>>, tensor<index, #sam.encoding< Crd, "d5", "", "dense", 0 : i64>>, tensor<f32, #sam.encoding< Val, "d0", "t", "", 0 : i64>>) -> (tensor<index, #sam.encoding< Crd, "d3", "t11-0,1", "dense", 1 : i64>>, tensor<f32, #sam.encoding< Val, "d0", "t", "", 0 : i64>>)
    %27 = "sam.generator"() : () -> tensor<index, #sam.encoding< Ref, "d0", "t3-0", "", 0 : i64>>
    %28 = "sam.repeat"(%27, %output_ref) : (tensor<index, #sam.encoding< Ref, "d0", "t3-0", "", 0 : i64>>, tensor<index, #sam.encoding< Ref, "d0", "t10-0,1", "dense", 0 : i64>>) -> tensor<index, #sam.encoding< Ref, "d0", "t3-0", "", 0 : i64>>
    %29 = "sam.repeat"(%28, %output_refs_8#2) : (tensor<index, #sam.encoding< Ref, "d0", "t3-0", "", 0 : i64>>, tensor<index, #sam.encoding< Ref, "d1", "t10-0,1", "dense", 0 : i64>>) -> tensor<index, #sam.encoding< Ref, "d1", "t3-0", "", 0 : i64>>
    %output_ref_41, %output_crd_42 = "sam.fiber_lookup"(%29) <{index_var = 3 : index, tensor_num = 3 : index}> : (tensor<index, #sam.encoding< Ref, "d1", "t3-0", "", 0 : i64>>) -> (tensor<index, #sam.encoding< Ref, "d3", "t3-0", "dense", 0 : i64>>, tensor<index, #sam.encoding< Crd, "d3", "t3-0", "dense", 0 : i64>>)

    //%output_crd_43, %output_refs_44:5 = "sam.joiner"(%output_crd_19, %output_crd_22, %output_inner_crd_39, %output_crd_42, %output_crd_19, %output_refs_20#0, %output_ref_21, %output_val_40, %output_ref_41, %output_refs_20#1) <{joinerOp = #sam<joiner_type Union>, operandSegmentSizes = array<i32: 5, 5>}> : (tensor<index, #sam.encoding< Crd, "d3", "", "dense", 0 : i64>>, tensor<index, #sam.encoding< Crd, "d3", "t9-0", "dense", 0 : i64>>, tensor<index, #sam.encoding< Crd, "d3", "t11-0,1", "dense", 1 : i64>>, tensor<index, #sam.encoding< Crd, "d3", "t3-0", "dense", 0 : i64>>, tensor<index, #sam.encoding< Crd, "d3", "", "dense", 0 : i64>>, tensor<f32, #sam.encoding< Val, "d0", "t", "", 0 : i64>>, tensor<index, #sam.encoding< Ref, "d3", "t9-0", "dense", 0 : i64>>, tensor<f32, #sam.encoding< Val, "d0", "t", "", 0 : i64>>, tensor<index, #sam.encoding< Ref, "d3", "t3-0", "dense", 0 : i64>>, tensor<index, #sam.encoding< Ref, "d3", "t4-0,1", "dense", 0 : i64>>) -> (tensor<index, #sam.encoding< Crd, "d3", "", "dense", 0 : i64>>, tensor<f32, #sam.encoding< Val, "d0", "t", "", 0 : i64>>, tensor<index, #sam.encoding< Ref, "d3", "t9-0", "dense", 0 : i64>>, tensor<f32, #sam.encoding< Val, "d0", "t", "", 0 : i64>>, tensor<index, #sam.encoding< Ref, "d3", "t3-0", "dense", 0 : i64>>, tensor<index, #sam.encoding< Ref, "d3", "t4-0,1", "dense", 0 : i64>>)
    %output_crd_43, %output_refs_44:5 = "sam.joiner"(%output_inner_crd, %output_crd_22, %output_inner_crd_39, %output_crd_42, %output_val, %output_ref_21, %output_val_40, %output_ref_41) <{joinerOp = #sam<joiner_type Union>, operandSegmentSizes = array<i32: 4, 4>}> : (tensor<index, #sam.encoding< Crd, "d3", "t6-0,1", "dense", 1 : i64>>, tensor<index, #sam.encoding< Crd, "d3", "t9-0", "dense", 0 : i64>>, tensor<index, #sam.encoding< Crd, "d3", "t11-0,1", "dense", 1 : i64>>, tensor<index, #sam.encoding< Crd, "d3", "t3-0", "dense", 0 : i64>>, tensor<f32, #sam.encoding< Val, "d0", "t", "", 0 : i64>>, tensor<index, #sam.encoding< Ref, "d3", "t9-0", "dense", 0 : i64>>, tensor<f32, #sam.encoding< Val, "d0", "t", "", 0 : i64>>, tensor<index, #sam.encoding< Ref, "d3", "t3-0", "dense", 0 : i64>>) -> (tensor<index, #sam.encoding< Crd, "d3", "", "dense", 0 : i64>>, tensor<f32, #sam.encoding< Val, "d0", "t", "", 0 : i64>>, tensor<index, #sam.encoding< Ref, "d3", "t9-0", "dense", 0 : i64>>, tensor<f32, #sam.encoding< Val, "d0", "t", "", 0 : i64>>, tensor<index, #sam.encoding< Ref, "d3", "t3-0", "dense", 0 : i64>>, tensor<index, #sam.encoding< Ref, "d3", "t4-0,1", "dense", 0 : i64>>)

    %30 = "sam.repeat"(%output_refs_8#0, %output_refs_44#3) : (tensor<index, #sam.encoding< Ref, "d1", "t10-0,1", "dense", 1 : i64>>, tensor<index, #sam.encoding< Ref, "d3", "t3-0", "dense", 0 : i64>>) -> tensor<index, #sam.encoding< Ref, "d3", "t10-0,1", "", 0 : i64>>
    %31 = "sam.array_val"(%30) <{stream_shape = array<i64: 1>}> : (tensor<index, #sam.encoding< Ref, "d3", "t10-0,1", "", 0 : i64>>) -> tensor<f32, #sam.encoding< Val, "d0", "t10-0,1", "", 0 : i64>>
    %32 = "sam.array_val"(%output_refs_44#1) <{stream_shape = array<i64: 1>}> : (tensor<index, #sam.encoding< Ref, "d3", "t9-0", "dense", 0 : i64>>) -> tensor<f32, #sam.encoding< Val, "d0", "t9-0", "", 0 : i64>>
    %33 = "sam.alu"(%output_refs_44#0, %32) <{aluOp = #sam<op_type Add>}> : (tensor<f32, #sam.encoding< Val, "d0", "t", "", 0 : i64>>, tensor<f32, #sam.encoding< Val, "d0", "t9-0", "", 0 : i64>>) -> tensor<f32, #sam.encoding< Val, "d0", "t", "", 0 : i64>>
    %34 = "sam.array_val"(%output_refs_44#3) <{stream_shape = array<i64: 1>}> : (tensor<index, #sam.encoding< Ref, "d3", "t3-0", "dense", 0 : i64>>) -> tensor<f32, #sam.encoding< Val, "d0", "t3-0", "", 0 : i64>>
    %35 = "sam.alu"(%output_refs_44#2, %34) <{aluOp = #sam<op_type Add>}> : (tensor<f32, #sam.encoding< Val, "d0", "t", "", 0 : i64>>, tensor<f32, #sam.encoding< Val, "d0", "t3-0", "", 0 : i64>>) -> tensor<f32, #sam.encoding< Val, "d0", "t", "", 0 : i64>>
    %36 = "sam.alu"(%33, %35) <{aluOp = #sam<op_type Add>}> : (tensor<f32, #sam.encoding< Val, "d0", "t", "", 0 : i64>>, tensor<f32, #sam.encoding< Val, "d0", "t", "", 0 : i64>>) -> tensor<f32, #sam.encoding< Val, "d0", "t", "", 0 : i64>>
    %37 = "sam.alu"(%36) <{aluOp = #sam<op_type Max>}> : (tensor<f32, #sam.encoding< Val, "d0", "t", "", 0 : i64>>) -> tensor<f32, #sam.encoding< Val, "d0", "t", "", 0 : i64>>
    %38 = "sam.alu"(%37) <{aluOp = #sam<op_type Max>}> : (tensor<f32, #sam.encoding< Val, "d0", "t", "", 0 : i64>>) -> tensor<f32, #sam.encoding< Val, "d0", "t", "", 0 : i64>>
    %39 = "sam.alu"(%31, %38) <{aluOp = #sam<op_type Mul>}> : (tensor<f32, #sam.encoding< Val, "d0", "t10-0,1", "", 0 : i64>>, tensor<f32, #sam.encoding< Val, "d0", "t", "", 0 : i64>>) -> tensor<f32, #sam.encoding< Val, "d0", "t", "", 0 : i64>>

    %output_inner_crd_45, %output_val_46 = "sam.spacc"(%output_crd_43, %output_crd_7, %39) <{order = 1 : index}> : (tensor<index, #sam.encoding< Crd, "d3", "", "dense", 0 : i64>>, tensor<index, #sam.encoding< Crd, "d1", "", "dense", 0 : i64>>, tensor<f32, #sam.encoding< Val, "d0", "t", "", 0 : i64>>) -> (tensor<index, #sam.encoding< Crd, "d3", "", "dense", 0 : i64>>, tensor<f32, #sam.encoding< Val, "d0", "t", "", 0 : i64>>)

    // Joiner with spacc and LS d3 t4
    %output_crd_19, %output_refs_20:2 = "sam.joiner"(%output_inner_crd_45, %output_crd_18, %output_val_46, %output_ref_17) <{joinerOp = #sam<joiner_type Intersect>, operandSegmentSizes = array<i32: 2, 2>}> : (tensor<index, #sam.encoding< Crd, "d3", "", "dense", 0 : i64>>, tensor<index, #sam.encoding< Crd, "d3", "t4-0,1", "dense", 0 : i64>>, tensor<f32, #sam.encoding< Val, "d0", "t", "", 0 : i64>>, tensor<index, #sam.encoding< Ref, "d3", "t4-0,1", "dense", 0 : i64>>) -> (tensor<index, #sam.encoding< Crd, "d3", "", "dense", 0 : i64>>, tensor<f32, #sam.encoding< Val, "d0", "t", "", 0 : i64>>, tensor<index, #sam.encoding< Ref, "d3", "t4-0,1", "dense", 0 : i64>>)

    %output_ref_47, %output_crd_48 = "sam.fiber_lookup"(%output_refs_20#1) <{index_var = 6 : index, tensor_num = 4 : index}> : (tensor<index, #sam.encoding< Ref, "d3", "t4-0,1", "dense", 0 : i64>>) -> (tensor<index, #sam.encoding< Ref, "d6", "t4-0,1", "dense", 1 : i64>>, tensor<index, #sam.encoding< Crd, "d6", "t4-0,1", "dense", 1 : i64>>)
    %40 = "sam.array_val"(%output_ref_47) <{stream_shape = array<i64: 1>}> : (tensor<index, #sam.encoding< Ref, "d6", "t4-0,1", "dense", 1 : i64>>) -> tensor<f32, #sam.encoding< Val, "d0", "t4-0,1", "", 0 : i64>>
    %41 = "sam.repeat"(%output_refs_20#0, %output_ref_47) : (tensor<f32, #sam.encoding< Val, "d0", "t", "", 0 : i64>>, tensor<index, #sam.encoding< Ref, "d6", "t4-0,1", "dense", 1 : i64>>) -> tensor<f32, #sam.encoding< Ref, "d6", "t", "", 0 : i64>>
    %42 = "sam.alu"(%41, %40) <{aluOp = #sam<op_type Mul>}> : (tensor<f32, #sam.encoding< Ref, "d6", "t", "", 0 : i64>>, tensor<f32, #sam.encoding< Val, "d0", "t4-0,1", "", 0 : i64>>) -> tensor<f32, #sam.encoding< Val, "d0", "t", "", 0 : i64>>
    %output_inner_crd_49, %output_val_50 = "sam.spacc"(%output_crd_48, %output_crd_19, %42) <{order = 1 : index}> : (tensor<index, #sam.encoding< Crd, "d6", "t4-0,1", "dense", 1 : i64>>, tensor<index, #sam.encoding< Crd, "d3", "", "dense", 0 : i64>>, tensor<f32, #sam.encoding< Val, "d0", "t", "", 0 : i64>>) -> (tensor<index, #sam.encoding< Crd, "d6", "t4-0,1", "dense", 1 : i64>>, tensor<f32, #sam.encoding< Val, "d0", "t", "", 0 : i64>>)
    %43 = "sam.generator"() : () -> tensor<index, #sam.encoding< Ref, "d0", "t5-0", "", 0 : i64>>
    %44 = "sam.repeat"(%43, %output_ref) : (tensor<index, #sam.encoding< Ref, "d0", "t5-0", "", 0 : i64>>, tensor<index, #sam.encoding< Ref, "d0", "t10-0,1", "dense", 0 : i64>>) -> tensor<index, #sam.encoding< Ref, "d0", "t5-0", "", 0 : i64>>
    %output_ref_51, %output_crd_52 = "sam.fiber_lookup"(%44) <{index_var = 6 : index, tensor_num = 5 : index}> : (tensor<index, #sam.encoding< Ref, "d0", "t5-0", "", 0 : i64>>) -> (tensor<index, #sam.encoding< Ref, "d6", "t5-0", "dense", 0 : i64>>, tensor<index, #sam.encoding< Crd, "d6", "t5-0", "dense", 0 : i64>>)
    %output_crd_53, %output_refs_54:2 = "sam.joiner"(%output_inner_crd_49, %output_crd_52, %output_val_50, %output_ref_51) <{joinerOp = #sam<joiner_type Union>, operandSegmentSizes = array<i32: 2, 2>}> : (tensor<index, #sam.encoding< Crd, "d6", "t4-0,1", "dense", 1 : i64>>, tensor<index, #sam.encoding< Crd, "d6", "t5-0", "dense", 0 : i64>>, tensor<f32, #sam.encoding< Val, "d0", "t", "", 0 : i64>>, tensor<index, #sam.encoding< Ref, "d6", "t5-0", "dense", 0 : i64>>) -> (tensor<index, #sam.encoding< Crd, "d6", "", "dense", 0 : i64>>, tensor<f32, #sam.encoding< Val, "d0", "t", "", 0 : i64>>, tensor<index, #sam.encoding< Ref, "d6", "t5-0", "dense", 0 : i64>>)
    %45 = "sam.array_val"(%output_refs_54#1) <{stream_shape = array<i64: 1>}> : (tensor<index, #sam.encoding< Ref, "d6", "t5-0", "dense", 0 : i64>>) -> tensor<f32, #sam.encoding< Val, "d0", "t5-0", "", 0 : i64>>
    %46 = "sam.alu"(%output_refs_54#0, %45) <{aluOp = #sam<op_type Add>}> : (tensor<f32, #sam.encoding< Val, "d0", "t", "", 0 : i64>>, tensor<f32, #sam.encoding< Val, "d0", "t5-0", "", 0 : i64>>) -> tensor<f32, #sam.encoding< Val, "d0", "t", "", 0 : i64>>
    "sam.fiber_write"(%output_crd) <{writeOp = #sam<write_type Crd>}> : (tensor<index, #sam.encoding< Crd, "d0", "t10-0,1", "dense", 0 : i64>>) -> ()
    "sam.fiber_write"(%output_crd_53) <{writeOp = #sam<write_type Crd>}> : (tensor<index, #sam.encoding< Crd, "d6", "", "dense", 0 : i64>>) -> ()
    "sam.fiber_write"(%46) <{writeOp = #sam<write_type Val>}> : (tensor<f32, #sam.encoding< Val, "d0", "t", "", 0 : i64>>) -> ()
    return %46 : tensor<f32, #sam.encoding< Val, "d0", "t", "", 0 : i64>>
  }
}

